/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package firstProject.app;

import firstProject.list.LinkedList;

import static firstProject.utilities.StringUtils.join;
import static firstProject.utilities.StringUtils.split;
import static firstProject.app.Calculator.getMessage;

import org.apache.commons.text.WordUtils;

public class App {
    public static void main(String[] args) {
        LinkedList tokens;
        tokens = split(getMessage());
        String result = join(tokens);
        System.out.println(WordUtils.capitalize(result));
    }
}
